name: telegram_mini_app
description: A simple Telegram Mini App built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_telegram_miniapp: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # Removed uses-material-design to avoid Roboto font loading errors
  # Using system fonts instead
  
  # Assets folder (for images used in Flutter code)
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/sample/
    - .env
  
  # Fonts configuration
  fonts:
    - family: Aeroport
      fonts:
        - asset: assets/fonts/AEROPORT-REGULAR-TRIAL.OTF
          weight: 400
        - asset: assets/fonts/AEROPORT-LIGHT-TRIAL.OTF
          weight: 300
        - asset: assets/fonts/AEROPORT-MEDIUM-TRIAL.OTF
          weight: 500
        - asset: assets/fonts/AEROPORT-BOLD-TRIAL.OTF
          weight: 700
        - asset: assets/fonts/AEROPORT-BLACK.OTF
          weight: 900
    - family: Aeroport Mono
      fonts:
        - asset: assets/fonts/AEROPORT-MONOSPACED-TRIAL.OTF
          weight: 400


